USE ZHYFOUNDRY_SPIDER;

DELIMITER $$
CREATE TRIGGER `TRIG_LATEST_TRACK_TIME` BEFORE INSERT ON `URL_TRACKER` FOR EACH ROW BEGIN
    SET NEW.LATEST_TRACK_TIME = CURRENT_TIMESTAMP;
END
$$
DELIMITER ;